# Generated by Django 5.2.16 on 2026-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatuschoices',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
