# Generated by Django 5.2.16 on 2026-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
